### ISSUE TITLE
After death - the camera does not work - spam log

### ISSUE THREAD

**Issue by Paradox75831004** [Zaggy1024/LC_OpenBodyCams#1]
![image](https://github.com/Zaggy1024/LC_OpenBodyCams/assets/72872478/52b3f207-7c43-4c36-9bee-ec74068bc4eb)
In our assembly - 018d2e1f-ADE5-6BF6-4B1A-8ddf2d6df104
At the start, everything works perfectly and smoothly, I changed the resolution of the camera screen and tried to run with it. There were no problems with Helmet_Camera...
After death on any planet - when you go into orbit - the camera does not work.
Only re-entry helps
Add your mod to our build and test it

**Comment by Zaggy1024** [comment]
Looks like this may be an issue that occurs when the body cam is attached to a dead player that gets removed when the current planet is unloaded. Shouldn't be too hard to fix hopefully.

**Comment by Zaggy1024** [comment]
Resolving this as I believe I've solved the issue in 4947d35, feel free to reopen it if the issue of the game rendering stopping and error spam happens again.
