### ISSUE TITLE
You did it! W Updates OBC on top!

### ISSUE THREAD

**Issue by HE70v** [Zaggy1024/LC_OpenBodyCams#12]
Just really happy you added that suggestion i made Good job.
 I'm glad you're always actively updating this. Just don't be losing sleep. But, your strides are not left unnoticed.
 Underrated mod fr. Nicely done.

https://github.com/Zaggy1024/LC_OpenBodyCams/assets/157659896/84935a6d-c5a8-484b-859a-8e2afafe82fd

**Comment by Zaggy1024** [comment]
Thanks!
