### ISSUE TITLE
[Bug] OpenBodyCam screen flickers green when switching cams

### ISSUE THREAD

**Issue by ajsglist** [Zaggy1024/LC_OpenBodyCams#15]
Occurring in OBC version [1.1.2]. Seems to be showing a blank (0,255,0) texture on cam switch, perhaps related to the emissivity?  Gif added below
![green_cam_flicker](https://github.com/Zaggy1024/LC_OpenBodyCams/assets/139426529/04bbf46b-533a-41c5-a7e6-8b006f52d02e)

**Comment by Zaggy1024** [comment]
That's intended, to mirror the behavior of the radar map screen. I could add an option to disable it, but I feel that it looks stranger to have them be mismatched.

**Comment by ajsglist** [comment]
a config option to disable it would be excellent

**Comment by Zaggy1024** [comment]
I'll get this into the next update hopefully!
