### ISSUE TITLE
Allow viewing of the body cam in the terminal

### ISSUE THREAD

**Issue by HE70v** [Zaggy1024/LC_OpenBodyCams#16]
Not entirely necessary but it'd be nice if you could have an option to unlock the camera at the terminal to be able to look at cams while still viewing the monitor

**Comment by Zaggy1024** [comment]
I might consider this as part of this mod to allow compatibility between this and TwoRadarMaps, but I think my priority would be to work with other mods that enable body cams in the terminal instead.

**Comment by Zaggy1024** [comment]
This is implemented in version 1.2.0!
