### ISSUE TITLE
Add an option to lower the graphics on the Body Cam.

### ISSUE THREAD

**Issue by broken-usb** [Zaggy1024/LC_OpenBodyCams#17]
Even while using HDLethalCompany to lower the game's graphics, the body cam will still render everything at normal quality. Adding a option to disable or lower the quality of the effects on the body could help more with performance.

**Comment by Zaggy1024** [comment]
The latest version will now copy the settings from the main camera, which HDLethalCompany applies its quality settings to. As far as having custom graphics settings for the body cam, that's something I may look into later, but it's a little bit more involved to add all the options one might desire.
