### ISSUE TITLE
Readd the replaced outside door ship cam (plus configurable)

### ISSUE THREAD

**Issue by zndrmn** [Zaggy1024/LC_OpenBodyCams#18]
It would be super cool if you could add back the previous ship camera and relocate it to a different screen.
Also giving players the ability to enable/disable the relocated ship camera would be great too

(for those wondering I enabled "DisableCameraWhileTargetIsOnShip" which is why it's blank in the screenshot)
![1966720_20240213000919_1](https://github.com/Zaggy1024/LC_OpenBodyCams/assets/77690119/7636f930-e6f7-4845-966a-f50f6bedccae)

**Comment by Zaggy1024** [comment]
That's unfortunately not really possible without me creating a new asset for the screens, which I don't really want to do for this mod. I would recommend looking at GeneralImprovements by Shaosil for more monitor customizations. Its BetterMonitors option allows you to reposition any camera.

One thing that is possible is to put the external camera on it while there isn't a valid target (including while the target is on the ship with that option on), but that's already on my roadmap and is a separate feature from this, so I'll close this, sorry.

**Comment by zndrmn** [comment]
No problem!
