### ISSUE TITLE
In the friend's room, the screen is all green

### ISSUE THREAD

**Issue by ZhuJap** [Zaggy1024/LC_OpenBodyCams#22]
![微信截图_20240216200433](https://github.com/Zaggy1024/LC_OpenBodyCams/assets/92317850/481137cc-8b66-46c4-a525-ad77d9dffd0e)
**"But after a period of time, the screen will return to normal. Please help me."**

**Comment by Zaggy1024** [comment]
Do you have a log file and context for how this happened? A video would help a lot.

**Comment by ZhuJap** [comment]
> 您有日志文件和上下文来说明这是如何发生的吗？视频会有很大帮助。

![微信截图_20240219132434](https://github.com/Zaggy1024/LC_OpenBodyCams/assets/92317850/c236605b-4d72-4f98-ad0f-3edc063034d5)

**Comment by ZhuJap** [comment]
> Would you be able to upload the full log file from an instance where the issue occurred? That error isn't abnormal from my experience, and hasn't caused issues that I've noticed.
![微信截图_20240220182307](https://github.com/Zaggy1024/LC_OpenBodyCams/assets/92317850/da95795c-1de3-440b-9c2c-bb41cf06d043)
[LogOutput.log](https://github.com/Zaggy1024/LC_OpenBodyCams/files/14342958/LogOutput.log)

**This is my log file, and the screen is green after I join my friend's room but it goes back to normal after a while**

**Comment by ZhuJap** [comment]
> Would you be able to upload the full log file from an instance where the issue occurred? That error isn't abnormal from my experience, and hasn't caused issues that I've noticed.

![微信截图_20240220183338](https://github.com/Zaggy1024/LC_OpenBodyCams/assets/92317850/77b7f7cf-31ad-4ec4-b129-138fde416175)
**When I re-entered, I was like this**

**Comment by Zaggy1024** [comment]
I encountered this while testing some other things, I assume you have the transition animation disabled?

I have a commit incoming that should fix this if so.

**Comment by ZhuJap** [comment]
> I encountered this while testing some other things, I assume you have the transition animation disabled?
> 
> I have a commit incoming that should fix this if so.

thank you
