### ISSUE TITLE
[Bug] green flicker on TARGET'S screen when radar switches

### ISSUE THREAD

**Issue by MasterEvilAce** [Zaggy1024/LC_OpenBodyCams#23]
Played with latest OpenBodyCams (and a bunch of other mods, most recent CullFactory, but could be completely related to OBC on its own.)

When someone in the ship changes the radar screen to a new TARGET player, the TARGET player's own first person screen will flash green, just like the openbodycams monitor.

While playing I witnessed green flashes occuring in the center of my screen. Other players mentioned this too. It happened while I was inside the facility, as well as outside (Offense), as well as custom moons and custom interiors.

It seems to be directly related to someone in the ship (it can even be yourself) flipping through players. The green flicker effect on the monitor is being rendered on player's own first person views while they're still alive, whenever the radar switches to them. So if there's only two players you should be able to switch between them and yourself repeatedly and you should see the flash.
It's possible this doesn't occur everytime, or only triggers when something bizarre happens (perhaps CullFactory is messing with the same camera, or AdvancedCompany, or some such.)

**Comment by Zaggy1024** [comment]
Do you have logs and a profile code that I can try to reproduce this with? I've never been able to reproduce this issue when it was reported, so it may be related to another mod causing errors to occur when tearing down the body cam rendering setup.

**Comment by Zaggy1024** [comment]
Also, is this a new issue in 1.2.2?

**Comment by DeathWrench** [comment]
I had this happen to me as well, I tried disabling the animation and it worked for a bit, but then a planet later, a static green rectangle went horizontally across my screen, rendering me partially blind. I could see it on my corpse right in front of my characters face.

**Comment by Zaggy1024** [comment]
> I had this happen to me as well, I tried disabling the animation and it worked for a bit, but then a planet later, a static green rectangle went horizontally across my screen, rendering me partially blind. I could see it on my corpse right in front of my characters face.

Again, do you have logs? It's very interesting that it happened even with the animation disabled, though, that means that something else must be interacting with the animation or the visibility of the mesh.

**Comment by Zaggy1024** [comment]
> [lc_LogOutput.log](https://github.com/Zaggy1024/LC_OpenBodyCams/files/14334888/lc_LogOutput.log) [lc_modlist.txt](https://github.com/Zaggy1024/LC_OpenBodyCams/files/14334890/lc_modlist.txt) I attached the log from the night and the modlist we use (I make a pack and send it to everyone.) Here is a videoclip of it happening. I am AFFM and when I switch through the cams, you can see the green lines appear on my screen when it switches to my own camera. https://www.dropbox.com/scl/fi/13bbptdxp6a7d8pd4ek69/AT-cm-7ArfQvRSIhmYzirk4xmpzQ.mp4?rlkey=v0vom3o8lck4acrqjz0dnvqvd&dl=0

It looks like maybe you have the BepInEx option set to disable Unity logs? That means there won't be any errors printed to the console that I'm looking for. :(

**Comment by Zaggy1024** [comment]
I put out version 1.2.3 a bit ago, which may affect this issue due to changing how I set up and tear down the body camera setup, if you could let me know if you get the issue again on that version.

If you end up playing again and think you might get the issue, please do make sure that the Unity logging is enabled.

**Comment by Zaggy1024** [comment]
Finally managed to reproduce this issue on my end, it was usually triggered by switching from a dead body to a player, especially with `DisableCameraWhileTargetIsOnShip` enabled, which would cause it to remain visible on the main camera permanently.

Fix is (finally) going out in 1.2.7, thank you to everyone who reporting the issue and provided info!
