### ISSUE TITLE
Loading Error

### ISSUE THREAD

**Issue by Qugar** [Zaggy1024/LC_OpenBodyCams#24]
Unfortunately, something is going wrong. Mod has not loaded, no monitors can be seen.

![grafik](https://github.com/Zaggy1024/LC_OpenBodyCams/assets/8191849/48f60653-ec32-456b-9e64-f75caf2184e1)

[LogOutput.log](https://github.com/Zaggy1024/LC_OpenBodyCams/files/14337283/LogOutput.log)

**Comment by Zaggy1024** [comment]
Hmm, that's curious, it seems like something must have destroyed the screen by the door before I try to access it. I'll put out a patch that should prevent this from causing it to break.

It looks like your save may have been corrupted, though: 

```
[Error  : Unity Log] IndexOutOfRangeException: Index was outside the bounds of the array.
Stack trace:
(wrapper dynamic-method) StartOfRound.DMD<StartOfRound::LoadShipGrabbableItems>(StartOfRound)
(wrapper dynamic-method) StartOfRound.DMD<StartOfRound::Start>(StartOfRound)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<StartOfRound::Start>?-1729473558(StartOfRound)
LethalLib.Modules.Items.StartOfRound_Start (On.StartOfRound+orig_Start orig, StartOfRound self) (at <4eedb4dc36094adcb65137cf81f2803d>:IL_0178)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<StartOfRound::Start>?-2026857184(StartOfRound)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<StartOfRound::Start>?-1225427846(StartOfRound)
LethalLib.Modules.Utilities.StartOfRound_Start (On.StartOfRound+orig_Start orig, StartOfRound self) (at <4eedb4dc36094adcb65137cf81f2803d>:IL_019C)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<StartOfRound::Start>?126438592(StartOfRound)
```

**Comment by Qugar** [comment]
That's not so bad, it's my test save anyway. :wink:

**Comment by Zaggy1024** [comment]
Pushed out v1.2.5 to fix this!

**Comment by Qugar** [comment]
The latest version with a new save file triggers exactly the same problem.

[LogOutput.log](https://github.com/Zaggy1024/LC_OpenBodyCams/files/14337542/LogOutput.log)

**Comment by Zaggy1024** [comment]
It looks like the error from OpenBodyCams is gone and it initialized correctly. If you're still having issues, it's likely that some other mod is the issue.

**Comment by Qugar** [comment]
Could it be an incompatibility with LethalSnap?

I just tested something else. I bought the Polaroid camera and this only happens when I load a saved game into the ship.

I'll have to see if they answer at LethalSnap, the last question from a week ago was simply ignored.

Tanks for your help. :smile:

**Comment by Zaggy1024** [comment]
> FYI: There are no more problems after uninstalling LethalSnap.

That's good to know, I did get a report of a similar error on Discord earlier today so maybe that was also related.

> Thanks for your help. 😄

No problem!
