### ISSUE TITLE
On new game this is the screen everyone except the host sees

### ISSUE THREAD

**Issue by Kayotik16** [Zaggy1024/LC_OpenBodyCams#27]
![image](https://github.com/Zaggy1024/LC_OpenBodyCams/assets/156811314/376e8244-2035-49e7-a6a3-cb78c5b55513)

**Comment by Zaggy1024** [comment]
I can't seem to reproduce this, can you provide more information?
- Profile code?
- Does this happen 100% of the time immediately upon joining a lobby without the host doing anything first?
- Are you up to date with 1.2.7?

**Comment by Zaggy1024** [comment]
Never mind, managed to reproduce this. It appears to only happen if you have the transition animation disabled.
