### ISSUE TITLE
view bodycam not working with darmuh terminal and camera not rendering when looking through terminal using darmuh

### ISSUE THREAD

**Issue by Tomveloper** [Zaggy1024/LC_OpenBodyCams#28]
i know it doesn't have official compatibility but maybe add a config option for levels of optimization on the camera rendering conditions, i want the camera to render whether i look at either the terminal screen or the ship right monitor and i don't expect that specifically to be added, just add an option to render when in ship, and maybe just render it if you are on the terminal, idk like i said it's not supposed to be compatible but it could be easily done for advanced users using the config. this is the best bodycam mod but it's not compatible with darmuh terminal and i really like both of these mods

**Comment by Zaggy1024** [comment]
darmuh is aware of this issue and is including a compatibility patch in their next update to enable the body cam when it is viewed in the terminal.
