### ISSUE TITLE
Framerate drops after last update.

### ISSUE THREAD

**Issue by WereWhusky** [Zaggy1024/LC_OpenBodyCams#31]
The framerate drops from the hundreds to 20-25 when looking at the monitor, no matter what settings I use or if the target is on ship or not, this issue did not existed on previous versions of the mod.

**Comment by Zaggy1024** [comment]
Do you have a profile code for me to test this with? I haven't experienced anything like that.

**Comment by Zaggy1024** [comment]
Closing this, as it works on my machine and there's been no update.
