### ISSUE TITLE
Displays black screen on launch

### ISSUE THREAD

**Issue by Tealdragon204** [Zaggy1024/LC_OpenBodyCams#36]
I have a whole list of mods, I can send them to you, but this one when booting displays a black screen on launch. Likely related to the new patch (As this modlist worked fine with it before)

**Comment by Zaggy1024** [comment]
The new patch as in v50? OpenBodyCams works with v50, so you may have a conflict causing an issue. Logs would help greatly.

**Comment by Tealdragon204** [comment]
Turns out it's LethalLevelLoader conflicting with the mod (Or one of the mods dependent on it) but since LethalLevelLoader displays a blank screen on the terminal and is thus completely borked. I will close the issue since although it may be an incompatibility, it's an incompatibility with either the borked dependency (LLL) or one of the mods reliant on it
