### ISSUE TITLE
camera quality

### ISSUE THREAD

**Issue by pil0lo** [Zaggy1024/LC_OpenBodyCams#39]
Mod : OpenBodyCams (https://thunderstore.io/c/lethal-company/p/Zaggy1024/OpenBodyCams/)
How do you make the camera quality good?
What should I do to improve the image quality of OpenBodyCams?
![1](https://github.com/Zaggy1024/LC_OpenBodyCams/assets/143984023/b5e78d3e-4481-49ae-ad9b-ae574863ecec)

Mod : Helmet Cameras (https://thunderstore.io/c/lethal-company/p/RickArg/Helmet_Cameras/)
Helmet Cameras mode is being released with better image quality.
![2](https://github.com/Zaggy1024/LC_OpenBodyCams/assets/143984023/611553a2-d4b9-4e75-b1b5-f30b89cf2686)

**Comment by Zaggy1024** [comment]
From the readme:

> `HorizontalResolution`: The horizontal resolution of the rendered view.

Increase that value and the image quality will improve.
