### ISSUE TITLE
Mod removed from thunderstore.io?

### ISSUE THREAD

**Issue by Slendykins** [Zaggy1024/LC_OpenBodyCams#4]
Hey Zaggy, been loving your mod as an alternative cam mod, feels more lightweight than the earlier implementations but now it looks to be gone or removed?

**Comment by Zaggy1024** [comment]
Thunderstore unfortunately didn't like the latest version I uploaded, so I'm waiting on their admins to reinstate it.

**Comment by Catpyre** [comment]
Huh, did they provide any info onto why they didn't like that version?? Thats so weird

**Comment by Zaggy1024** [comment]
Looks like it had to do with my method of implementing mod compatibility features, but it's been reinstated. I'll have to check out other methods of implementing those.
