### ISSUE TITLE
Ship upgrade active after mod update

### ISSUE THREAD

**Issue by FaithOfSin** [Zaggy1024/LC_OpenBodyCams#40]
Hi there!
I just updated the mod (to 2.0.6) and in game I realized that the body cam didn´t work any more.
I searched for the issue and after a while I noticed, that in the setting the ship upgrade was suddenly active (only activates the body cam on the monitor if you buy it in the store).

I don´t know if this was on purpose but I wanted to let you know about this.
I am not sure any more if I deactivated it when I first installed the mod and if it´s active by default - but I had it deactivated for sure before the update.

**Comment by Zaggy1024** [comment]
Yeah, that was actually my bad for not initially setting the config option to the intended default of enabled. It was corrected in a config migration step, so now that you're on a version past that point, it should not change again.

Sorry for the inconvenience!
