### ISSUE TITLE
[Bug] Setting ExternalCameraEmissiveColor to a different color creates a strange effect

### ISSUE THREAD

**Issue by zndrmn** [Zaggy1024/LC_OpenBodyCams#41]
Setting ExternalCameraEmissiveColor to a different color causes the posterization effect to mess with the camera a bit
(vanilla behaves normally and the posterization effect doesn't mess with the ship camera)

Or maybe it's just the vanilla emissive color that's showing on top of the custom color
Edit: After some more testing it seems like it only happens with some colors 

`ExternalCameraEmissiveColor = 0.05, 0.13, 0.05`

https://github.com/Zaggy1024/LC_OpenBodyCams/assets/77690119/580b980b-2dcd-4736-ac64-b96be02310b7

https://github.com/Zaggy1024/LC_OpenBodyCams/assets/77690119/aaa39efb-8f30-41b1-9470-73658e8b72a9

**Comment by Zaggy1024** [comment]
Unfortunately, this is not a bug. It's just the nature of how the posterization filter works, you can see it in the shading on the wall in dark areas as well.

The option is there for people that want to spend the time to tweak that screen, but I don't have any values to recommend for it.

It's possible that there are other values that could be adjusted to make it appear more similar to the body cam, but that would take some experimentation.

**Comment by zndrmn** [comment]
> Unfortunately, this is not a bug. It's just the nature of how the posterization filter works, you can see it in the shading on the wall in dark areas as well.

I kinda figured that it was just the posterization being weird after doing some more testing.

> It's possible that there are other values that could be adjusted to make it appear more similar to the body cam, but that would take some experimentation.

yea that's pretty much what I was trying to achieve. I actually just used the same emission color as the bodycam.
tho I haven't been able to see how close it looks because I don't have a second player to test it.

**Comment by Zaggy1024** [comment]
It's pretty easy to test out the body cams if you spawn in some radar boosters with [LethalDevMode](https://thunderstore.io/c/lethal-company/p/megumin/LethalDevMode/) or a similar mod.

If you have LethalConfig and enable the `DisplayOriginalScreenWhenDisabled` option, you can switch between the external camera and the body cams with the `EnableCamera` option.
