### ISSUE TITLE
doesnt let you in any game with that mod

### ISSUE THREAD

**Issue by pixelflap** [Zaggy1024/LC_OpenBodyCams#43]
^^^ just throws "an error occurred" when joining any lobby

i am 100% sure that this mod causes it cause i disabled all of them and kept enabling them one by one and with that mod it started to cause errors

**Comment by pixelflap** [comment]
it somewhy enabled all compatibility options by default and that's what was causing issues, case closed

**Comment by pixelflap** [comment]
done in 7 minutes lmao

**Comment by pixelflap** [comment]
P.S you need to rollback to 2.1.0 in order for this to work so the issue is open plz fix

**Comment by Zaggy1024** [comment]
Could you provide logs and a mod profile code so I can reproduce this? 

> it somewhy enabled all compatibility options by default and that's what was causing issues, case closed

> P.S you need to rollback to 2.1.0 in order for this to work so the issue is open plz fix

It's unclear which of these is correct, does one of the compatibility options cause the issue you're encountering?

**Comment by pixelflap** [comment]
fixed with latest update
