### ISSUE TITLE
Client-Side issue

### ISSUE THREAD

**Issue by zombiedrakenkiller** [Zaggy1024/LC_OpenBodyCams#45]
I normally was using Helmet-Cameras for a body cam.

I wanted to get General improvements And i couldnt use that mod anymore, so i switched to OpenBodyCams since it said it was categorised as Client-Side on Thunderstore as Helmet-Cameras was. Is it wrongly categorised or am i running into some connecting issues?
Once i dissable OpenBodyCams i am able to join more lobbies than when i do have it active.

**Comment by Zaggy1024** [comment]
It appears to work for me, but you may encounter issues if you have LethalLib installed and don't disable the unlockable.

Could you get logs from a join attempt?

**Comment by Veloxi0** [comment]
I can confirm that the same issue was happening for me, and disabling the unlockable resolves it so I can join servers.
Here's my log from starting the game and attempting to join 3 servers, hopefully it helps.
[LogOutput.log](https://github.com/user-attachments/files/15993341/LogOutput.log)

**Comment by Zaggy1024** [comment]
I forgot to close this out, but it is expected that if LethalLib is installed, there will be issues with connecting to unmodded clients.

It seems a bit strange to me to join unmodded lobbies with LethalLib anyway, I'm not sure there's any API that it provides that doesn't require synchronization with the server.
