### ISSUE TITLE
Not compatible with "GeneralImprovements" by ShaosilGaming

### ISSUE THREAD

**Issue by junnlives** [Zaggy1024/LC_OpenBodyCams#47]
Currently running GeneralImprovements v1.4.4 + OpenBodyCams v2.3.1 and cannot get both to work whatsoever.
Throws this error in console when server is started
![image](https://github.com/user-attachments/assets/cf55cfbd-31e2-41b5-a873-a292d327e904)

Profile code:
01920d32-1b57-98e8-407a-8e9248cff0c8 (132 mods, tested with every mod)

Would be awesome if compatibility could be restored as this was previously working about a week or two ago before I returned.

**Comment by Zaggy1024** [comment]
Ah, I had forgotten this was still broken in the live version. This is due to an issue in the API for GeneralImprovements, I'll push an update with this fixed shortly.

**Comment by Zaggy1024** [comment]
It looks like this can be worked around by setting GeneralImprovements' `AddMoreBetterMonitors` option to `false` when `UseBetterMonitors` is also `false`.
