### ISSUE TITLE
Visual bug caused by the mod.

### ISSUE THREAD

**Issue by G1gg1L3sG** [Zaggy1024/LC_OpenBodyCams#51]
I've noticed that whenever I bought the bodycam through the terminal and looking at my character in third person view or emoting or viewing self from a mirror, it has this red sprite in the body?? Though this occurs only when you do it in the first run of the game meaning starting a new save. When starting another run, the red sprite completely disappeared. Another way to make it disappear is that to quit to the main menu and load the save. Not exactly sure if this caused by the mod or others and I don't want to load up save or start another run every time it appears. Another thing is, whenever I try to purchase ship upgrades or modded ones, the red sprite appears despite not purchasing the bodycam. Sometimes, the red sprite doesn't occured at all which is rare.

On another, I tested to run the game without bodycam installed and all seem to be well whenever I try to purchase upgrades for the ship. The red sprite doesn't appear anymore.

As much as I want this bodycam mod to be in my modlist, I hope there'll be a fix to the visual bug.

Thanks for taking your time diving into this problem. FYI, The image uploaded was just the character emoting T-Pose. It's not a bug. And my apologies if there's already a fix for this.
![image_2024-10-01_191848504](https://github.com/user-attachments/assets/cd60aeba-1c09-44db-8b51-eae8cd59d3c5)

**Comment by G1gg1L3sG** [comment]
Nevermind, after doing thorough investigation, it was Control Company Addons because there's a feature where you press a key which is set to Y as a default to enable ESP cheat to see players through the wall. When you typed 'body' on the terminal, it hits the Y key which why it enables. I knew I shouldn't submit an issue and could've done it anyway if I was not feeling lazy. So this settles it if anyone has this problem. 

Case closed.

**Comment by Zaggy1024** [comment]
Oh, glad you figured this out. It didn't seem like it could be caused by OpenBodyCams lol

**Comment by G1gg1L3sG** [comment]
Yeah, my bad. It made me think that your mod causes it because I'm able to recreate the issue whenever I had your mod installed. I knew it myself I shouldn't submit a ticket right away. My modlist goes on 200+ mods and it takes me hours.
