### ISSUE TITLE
Not working with some mods and dont appear in store

### ISSUE THREAD

**Issue by MochyPei** [Zaggy1024/LC_OpenBodyCams#58]
I installed mod to my modpack, and in logs, and in config, mod loads, but on screen is nothing appears, and in store is no new ship upgrades. When i tried to remove all mods that i have, and install openbodycam, lethalconfig, lethallib & hookgenpatcher (for purchasing in store), camera appeared on screen, and works, but, still can't buy it.

Here's logs with only these 3 mods
[log_clean_mods.log](https://github.com/user-attachments/files/17324697/log_clean_mods.log)
And with all my mods
[log_full_mods.log](https://github.com/user-attachments/files/17324601/log_full_mods.log)

**Comment by Zaggy1024** [comment]
```
[Error  :OpenBodyCams] Failed to load the asset bundle, some features may be missing.
```

Looks like however you installed the mod, it didn't manage to find the asset bundle in the folder with the OpenBodyCams dll.

**Comment by MochyPei** [comment]
> it didn't manage to find the asset bundle in the folder with OpenBodyCams.dll.

What kind of asset bundle? Where i need to get it? When i installed mod, it's nothing but dll only

**Comment by Zaggy1024** [comment]
It's included in the Thunderstore package zip. How are you installing the mod? Mod managers will download the whole package and extract all files into a folder in plugins, including the `openbodycams` bundle file.

**Comment by MochyPei** [comment]
> How are you installing the mod?

I just downloaded it from thunderstore page and put dll file from archive to plugins folder

**Comment by Zaggy1024** [comment]
Ah, forgot to get back to this issue, but you cannot copy only the dll and have it work, it needs the asset bundle file as well.
