### ISSUE TITLE
[Bug] Bootup issue after MoreCompany 1.10.2 update

### ISSUE THREAD

**Issue by ajsglist** [Zaggy1024/LC_OpenBodyCams#59]
Hey there,

Getting a bootup error after updating to the newest release of MoreCompany.  OBC seems to function, but they start purchased/unlocked (with no antenna) despite having the settings to make it a purchased upgrade.

```
[21:25:33.9913965] [Info   :   BepInEx] Loading [OpenBodyCams 2.4.5]
[21:25:34.0594121] [Info   :OpenBodyCams] Successfully loaded OpenBodyCams assets.
[21:25:34.2604571] [Info   :OpenBodyCams] Patched UnlockableSuit to spawn cosmetics for both perspectives on all players.
[21:25:34.7775745] [Info   :OpenBodyCams] Last config version is 2.4.5.
[21:25:34.7835754] [Error  : Unity Log] TypeLoadException: Could not resolve type with token 01000103 from typeref (expected class 'MoreCompany.ClientReceiveMessagePatch' in assembly 'MoreCompany, Version=1.7.6.0, Culture=neutral, PublicKeyToken=null')
Stack trace:
OpenBodyCams.Utilities.Cosmetics.Initialize (HarmonyLib.Harmony harmony) (at <9f7f0c7353f64b9ab05c72a664f861a3>:IL_007C)
OpenBodyCams.Plugin.Awake () (at <9f7f0c7353f64b9ab05c72a664f861a3>:IL_0A4E)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset:OnEnable()
```

Cheers

**Comment by ajsglist** [comment]
It's also worth noting that there is an OBC issue related to the new hat.

For Host, the hat is always hidden on the OBC bodycam nominally.  When a TME emote is performed, the TME first person bodycam is obscured by the hat covering the cam.

![image](https://github.com/user-attachments/assets/4ce25a9f-bf89-442e-bdc6-705643f3e475)

When the emote is cancelled and the OBC returns to first person, the bodycam reverts to it's nominal state and is fine.

![image](https://github.com/user-attachments/assets/d8f13efd-dafa-4f2f-9925-168c798180cc)

However it's a different story for non-host players.  Non-host players connected to the lobby will observed the hat obscuring the OBC bodycam even in the default state, in the absence of emoting or switching to the TME first person camera

![image](https://github.com/user-attachments/assets/c5455bc8-15a2-4ce8-972d-03e66a3fb2d6)

**Comment by Zaggy1024** [comment]
With regard to MoreCompany, it would be best to just disable the compatibility option for it in OpenBodyCams. The patch can't be updated until [this PR](https://github.com/notnotnotswipez/MoreCompany/pull/105) is merged, and the MoreCompany patch failing is probably causing the ship upgrade to never be registered.

I'm unsure if it's also causing the hat visibility issues, though, I'll have to look into that.

**Comment by Zaggy1024** [comment]
The MoreCompany local player cosmetics patch has been updated in 2.5.0 so that it doesn't cause anything else to break, so cosmetics should no longer obstruct the camera.

However, I'll close this once that PR is merged.

**Comment by ajsglist** [comment]
Reasonably sure this is fixed on OBC's end, closing
