### ISSUE TITLE
Offtopic question

### ISSUE THREAD

**Issue by V1Htor** [Zaggy1024/LC_OpenBodyCams#6]
Sorry for using issues. But, there are already 3 camera mods, which one is best and why there are so many?

**Comment by Zaggy1024** [comment]
There are a few reasons that I made this mod despite there being two others already:

- I wasn't happy that the other two mods (as far as I know) are closed-source, hence the name of this mod.
- The FPS hit from running Helmet_Cameras was unacceptable to me, and reading the decompiled code of Solos_Bodycams made me believe there was performance left on the table there as well. There may still be more performance to squeeze out of this mod, but I think it's an improvement at least.
- Neither mod displayed the first person viewmodel for other players, and showed duplicate arms/hands for the local player. I've implemented a system to hide the third person model/cosmetics and show the first person arms/item positioning in the camera.

With those three points, plus the customization I've implemented into it, I'll let you be the judge.

**Comment by V1Htor** [comment]
Thanks for answering. My friends suffered from performance drops when using custom models and other cam mods, i wonder could that be related, so i'll stick to your. Also, does mod show you from other's perspective as flying head too, or it renders fully?

**Comment by Zaggy1024** [comment]
As I mentioned, it shows/hides models based on the body camera's perspective, so no, no flying heads/arms.
