### ISSUE TITLE
[Request] Option to replace bodycam with InternalCam when target is on ship

### ISSUE THREAD

**Issue by ajsglist** [Zaggy1024/LC_OpenBodyCams#63]
Hey there,

Currently using GI in conjunction with OBC and we have the default state of the monitor to display the internal cam.  If possible, it would be nice to have the option to fallback to this cam when the target is on the ship.

Cheers

![image](https://github.com/user-attachments/assets/d500faad-654d-4a55-9427-5ba9e53958a4)

**Comment by Zaggy1024** [comment]
It should do that if you combine theoption to disable the camera when its target is on the ship with the one to display the original screen when the body cam is off.

**Comment by ajsglist** [comment]
oh, perfect

thanks
