### ISSUE TITLE
FPS drops with 1.0.14

### ISSUE THREAD

**Issue by Foxyr1s** [Zaggy1024/LC_OpenBodyCams#8]
Since version 1.0.14, FPS has dropped by 20%. Everything is stable on version 1.0.13.
I tried turning the new feature "DisableInternalShipCamera" on and off - it didn't help.

**Comment by Foxyr1s** [comment]
![v1013](https://github.com/Zaggy1024/LC_OpenBodyCams/assets/145286769/75bc4d75-b544-49b9-9ba6-4f96fa22f339)
![v1014](https://github.com/Zaggy1024/LC_OpenBodyCams/assets/145286769/b2dd7792-413e-47a7-a000-4d95af0b2c87)

**Comment by Zaggy1024** [comment]
Just pushed out an update 1.0.16 that should fix this issue, thank you for reporting it!

Feel free to open a new issue if you feel that performance on 1.0.16 isn't at the level it was in 1.0.13, since other changes may have affected performance as well.
