### ISSUE TITLE
[Incompatibility] GeneralImprovements

### ISSUE THREAD

**Issue by NilaierMusic** [Zaggy1024/LC_OpenBodyCams#9]
I'm using OpenBodyCams 1.0.16 and [GeneralImprovements](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements) 1.1.1. It looks like body cam doesn't render on any of the big monitors, but it does render on the smaller ones.
![Lethal_Company_tlswvZWXO9](https://github.com/Zaggy1024/LC_OpenBodyCams/assets/86863646/148f9f06-caca-4408-9e6b-93ad78a824a4)
![image](https://github.com/Zaggy1024/LC_OpenBodyCams/assets/86863646/3002cf4d-1046-4117-a694-0a62fe6befdd)

**Comment by Zaggy1024** [comment]
Ah, I messed up the references for the big monitors. I'll push out (yet another) update shortly.

**Comment by Zaggy1024** [comment]
Pushed update 1.0.17!
